
name: File_Presence_Check_on_Merge

on:
  merge:
    branches: ["main"]

jobs:
  file_validation_job_onMerge:
    name: file_validation_on_merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: run_file_presence_on_merge
        run: python check_required_files.py