
name: File_Presence_Check_on_Merge

on:
  push:
    branches: ["main"]

jobs:
  file_validation_job_onMerge:
    name: file_validation_on_merge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: run_file_presence_on_merge
        run: python check_required_files.py

# Configure AWS credentials

      - name: AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:      ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region:             ${{ secrets.AWS_REGION }}

# Check if log group exists, create if it doesn't. Output will be sent to dev/null if resource already exists.

      - name: Check or create log group
        run:  aws logs create-log-group --log-group-name "${{ secrets.LOG_GROUP_NAME_PROD }}" 2>/dev/null || true

# Assign a name to this log stream using UTC timestamp

      - name: Create log stream name
        run: echo "STREAM_NAME=$(date -u +%Y%m%dT%H%M%SZ)" >> "$GITHUB_ENV"

# Create the stream and push log values

      - name: Create stream and push logs
        run: |
          aws logs create-log-stream \
            --log-group-name "${{ secrets.LOG_GROUP_NAME_PROD }}" \
            --log-stream-name "$STREAM_NAME" || true

          # CloudWatch event timestamp in ms
          TS=$(($(date -u +%s)*1000))

          # Turn arrays into plain text
          MISSING='${{ join(fromJSON(steps.file_check.outputs.missing_files_output), ' , ') }}'
          REQUIRED='${{ join(fromJSON(steps.file_check.outputs.required_files_output), ' , ') }}'

          aws logs put-log-events \
            --log-group-name "${{ secrets.LOG_GROUP_NAME_PROD }}" \
            --log-stream-name "$STREAM_NAME" \
            --log-events '[{"timestamp": '"$TS"', "message": "Workflow='"$GITHUB_WORKFLOW"' SHA='"$GITHUB_SHA"' Actor='"$GITHUB_ACTOR"' RunID='"$GITHUB_RUN_ID"' Job='"$GITHUB_JOB"' Repo='"$GITHUB_REPOSITORY"' Branch='"$GITHUB_REF_NAME"' Event='"$GITHUB_EVENT_NAME"' Missing_Files='"$MISSING"' Files_Found='"$REQUIRED"'"}]'

